package ocdiary.riteclicker;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import ocdiary.riteclicker.init.RiteClickerItems;
import ocdiary.riteclicker.proxy.CommonProxy;

@Mod(modid = RiteClicker.MODID, name = RiteClicker.NAME, version = RiteClicker.VERSION)
public class RiteClicker {
    /**
     * RiteClicker strings
     */
    //RiteClicker ref stuff
    public static final String MODID = "riteclicker";
    public static final String NAME = "Rite Clicker";
    public static final String VERSION = "1.12_1";
    //SERVER FILES
    public static final String CLIENTPROXY = "ocdiary.riteclicker.proxy.ClientProxy";
    public static final String SERVERPROXY = "ocdiary.riteclicker.proxy.CommonProxy";
    //MCMOD stuff
    private static final String DESCRIPTION = "Adds the simple functionality of right clicking dirt, grass, or farmland dropping pebbles which can be made into cobblestone. Its main use is for skyblock style maps.";
    private static final String LOGOFILE = "assets/"+MODID+"/logo.png";


    public static Configuration config;

    /**
     * Config variables
     * */
    public static boolean sneakOn;
    public static boolean defaultWorld;
    public static boolean gogWorld;
    public static String soundLoc;
    public static String dropName;
    public static String blockName;
    public static String blockedWorlds;


    /**
     * Create a mod instance
     */
    @Mod.Instance(MODID)
    public static RiteClicker instance;

    /**
     * Setup proxy
     */
    @SidedProxy(serverSide = SERVERPROXY, clientSide = CLIENTPROXY)
    public static CommonProxy proxy;


    /**
     * Init all the mod stuffs
     */
    //PRE
    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        System.out.println(NAME + " is loading!");
        proxy.preInit();

        config = new Configuration(event.getSuggestedConfigurationFile());
        config();

         //I will now generate a mcmod.info file
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.modId = MODID;
        data.name = NAME;
        data.version = VERSION;
        data.authorList.add("OCDiary");
        data.credits = "Thanks to the Forge FML guys (you rock) and OCDiary";
        data.description = DESCRIPTION;
        data.logoFile = LOGOFILE;
    }
    //INIT
    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        proxy.init();
        MinecraftForge.EVENT_BUS.register(instance);
    }
    //POST
    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        proxy.postInit();
        System.out.println(NAME + " has finished loading!");
    }


    /**
     * Now for registering models etc
     * */
    @Mod.EventBusSubscriber
    public static class RegHandler{
        //Item reg stuff
        @SubscribeEvent
        public static void registerItems(RegistryEvent.Register<Item> event) {
            RiteClickerItems.register(event.getRegistry());
        }
        @SubscribeEvent
        public static void registerItems(ModelRegistryEvent event) {
            RiteClickerItems.registerModels();
        }
        //Block reg event
        @SubscribeEvent
        public static void registerBlocks(RegistryEvent.Register<Block> event) {
        }
        @SubscribeEvent
        public static void registerModels(ModelRegistryEvent event) {
            RiteClickerItems.registerModels();
        }
    }

    public static void config()
    {
        MinecraftForge.EVENT_BUS.register(instance);

        //, minecraft:grass_path, minecraft:farmland, minecraft:dirt

        String CLICKERCONF = "general" + "." + "Rite Clicker";
        config.addCustomCategoryComment(CLICKERCONF, "Here you can make changes to the mod features.");
        sneakOn = config.get(CLICKERCONF, "Do you want the right click function to only work when sneaking?", true).getBoolean();
        soundLoc = config.get(CLICKERCONF, "Sound that should be played when block is right clicked:", "block.grass.hit").getString();
        dropName = config.get(CLICKERCONF, "Item that should be dropped on right click:", "riteclicker:pebs").getString();
        blockName = config.get(CLICKERCONF, "Blocks that should drop the pebbles:", "minecraft:grass, minecraft:grass_path, minecraft:farmland, minecraft:dirt").getString();
        blockedWorlds = config.get(CLICKERCONF, "Here you can specify the world types RiteClicker should NOT work in", "default, customized, largeBiomes, amplified, flat, botania-skyblock").getString();

        if (config.hasChanged()) {
            config.save();
        }
    }
}